// Generated by scripts/render-shell-palette from tokens.toml.
pragma Singleton

import QtQuick

QtObject {
    readonly property color background: "#14100d"
    readonly property color surface: "#1c1612"
    readonly property color surfaceHigh: "#2a211a"
    readonly property color text: "#f2e6d8"
    readonly property color muted: "#a39483"
    readonly property color accent: "#e2733f"
    readonly property color accentText: "#2a0f05"
    readonly property color shadow: "#000000"
    readonly property color critical: "#f0435a"
    readonly property string uiFont: "Adwaita Sans"
}
