#!/usr/bin/env python3
# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate committed unlock artwork with Pillow/FreeType and Adwaita Sans."""

import argparse
from pathlib import Path
import struct
import sys
import tomllib
import zlib

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / 'installer'))
from emaki_installer import grub_screen as screen  # noqa: E402


def png(image):
    """Opaque RGB, no row filters: readable by GRUB and the dependency-free tests."""
    width, height = image.size
    pixels = image.tobytes()
    raw = b''.join(b'\0' + pixels[y * width * 3:(y + 1) * width * 3]
                   for y in range(height))

    def chunk(name, body):
        return struct.pack('>I', len(body)) + name + body + struct.pack('>I', zlib.crc32(name + body))

    return (b'\x89PNG\r\n\x1a\n'
            + chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 2, 0, 0, 0))
            + chunk(b'tEXt', b'Copyright\0Copyright (C) 2026 Artur Yakymenko')
            + chunk(b'tEXt', b'License\0SPDX-License-Identifier: GPL-3.0-or-later')
            + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def picture(font_path, colors, width, height, variant, state):
    # Same proportions, rasterized separately at each native resolution.
    size = round(width * 36 / 1024)
    font = ImageFont.truetype(str(font_path), size)
    if font.getname()[0] != 'Adwaita Sans':
        raise ValueError('the artwork requires Adwaita Sans')
    margin = round(width * 0.12)
    while max(font.getlength(line) for line in (*screen.TEXT, screen.WRONG, screen.CHECKING)) > width - 2 * margin:
        size -= 1
        font = ImageFont.truetype(str(font_path), size)
    image = Image.new('RGB', (width, height), colors['background'])
    draw = ImageDraw.Draw(image)
    # The invisible 4px terminal and its black cursor occupy the first 32px.
    # Blend that reserved band into the warm field without a visible hard edge.
    background = image.getpixel((0, 0))
    for y in range(96):
        amount = max(0, (y - 32) / 64)
        color = tuple(round(channel * amount) for channel in background)
        draw.line((0, y, width - 1, y), fill=color)
    line_height = round(size * (1.75 if variant == 'A' else 2.0))
    # Centre the five-line block, reserving its retry line so nothing jumps.
    middle = height // 2
    status = screen.CHECKING if state == 'checking' else screen.WRONG
    for index, line in enumerate((*screen.TEXT, status)):
        if index == len(screen.TEXT) and state == 'unlock':
            continue
        color = colors['accent'] if index == len(screen.TEXT) and variant != 'A' else colors['text']
        left, top, right, bottom = draw.textbbox((0, 0), line, font=font)
        x = (width - (right - left)) // 2 - left
        y = middle + (index - 2) * line_height - (bottom - top) // 2 - top
        draw.text((x, y), line, font=font, fill=color)
    if variant == 'C':
        y = middle - 3 * line_height
        half = round(width * 0.032)
        draw.rectangle((width // 2 - half, y, width // 2 + half, y + 1), fill=colors['accent'])
    return image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', type=Path, default=Path('/usr/share/fonts/Adwaita/AdwaitaSans-Regular.ttf'))
    parser.add_argument('--output', type=Path, default=screen.ARTWORK)
    parser.add_argument('--check', action='store_true', help='compare regenerated bytes without writing')
    args = parser.parse_args()
    tokens = tomllib.loads((ROOT / 'tokens.toml').read_text())
    colors = {name: '#' + value for name, value in tokens['color'].items()}
    for variant in ('A', 'B', 'C'):
        for width, height in screen.SIZES:
            for state in ('unlock', 'wrong', 'checking'):
                data = png(picture(args.font, colors, width, height, variant, state))
                path = args.output / variant / f'{state}-{width}x{height}.png'
                if args.check:
                    if path.read_bytes() != data:
                        raise SystemExit(f'artwork needs regeneration: {path}')
                else:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_bytes(data)
    print('Unlock artwork is current.' if args.check else 'Wrote all three unlock variants.')


if __name__ == '__main__':
    main()
