#!/usr/bin/env python3
# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
"""Exercise automatic mirror upkeep only inside disposable roots."""
import configparser
import json
import os
from pathlib import Path
import shlex
import shutil
import runpy
import subprocess
import tempfile
import unittest
import warnings

ROOT = Path(__file__).resolve().parents[1]
POLICY = runpy.run_path(str(ROOT / 'upkeep/emaki-refresh-mirrors'))
LEGACY = (b'# Arch Linux mirrorlist generated by Reflector\n'
          b'# With: reflector --protocol https --latest 10 --sort rate --connection-timeout 3 '
          b'--download-timeout 3 --save /tmp/emaki-mirrors-test123/mirrorlist\n'
          b'Server = https://old.invalid/$repo/os/$arch\n'
          b'Server = https://old2.invalid/$repo/os/$arch\n'
          b'Server = https://old3.invalid/$repo/os/$arch\n')
FRESH = (b'# New mirrors\nServer = https://fresh.invalid/$repo/os/$arch\n'
         b'Server = https://fresh2.invalid/$repo/os/$arch\n'
         b'Server = https://fresh3.invalid/$repo/os/$arch\n')


class MirrorRefreshTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix='emaki-mirrors-test-')
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.mirrors = self.root / 'etc/pacman.d/mirrorlist'
        self.mirrors.parent.mkdir(parents=True)
        self.mirrors.write_bytes(LEGACY)
        self.mirrors.chmod(0o644)
        self.state = self.root / 'var/lib/emaki/mirror-refresh/sha256'
        self.calls = []

    def run_probe(self, command, **options):
        self.calls.append((command, options))
        Path(command[-1]).write_bytes(FRESH)

    def refresh(self, run=None, **kwargs):
        POLICY['refresh'](self.root, run or self.run_probe, **kwargs)

    def test_recognized_installer_list_refreshes_and_tracks_successive_results(self):
        self.refresh()
        self.assertEqual(self.mirrors.read_bytes(), FRESH)
        self.assertEqual(self.mirrors.stat().st_mode & 0o777, 0o644)
        self.assertEqual(self.state.read_text(), POLICY['digest'](FRESH))
        self.refresh()
        self.assertEqual(len(self.calls), 2)
        command, options = self.calls[0]
        self.assertEqual(command[:-2], ['reflector', '--protocol', 'https', '--latest', '10',
                                       '--sort', 'rate', '--connection-timeout', '3',
                                       '--download-timeout', '3'])
        self.assertEqual(options, {'check': True, 'timeout': 60})
        self.assertFalse(Path(command[-1]).exists())

    def test_released_iso_list_is_adopted_exactly(self):
        # The fixture's first two lines are repository metadata, not ISO bytes.
        released = (ROOT / 'tests/fixtures/mirrorlist-0.2.0.txt').read_bytes().split(b'\n', 2)[2]
        self.mirrors.write_bytes(released)
        self.refresh()
        self.assertEqual(self.mirrors.read_bytes(), FRESH)
        self.assertEqual(self.state.read_text(), POLICY['digest'](FRESH))
        self.assertEqual(len(self.calls), 1)
        self.state.unlink()
        self.calls.clear()
        for edited in (released + b'# Local choice.\n',
                       released.replace(b'2026-06-10', b'2026-06-11'),
                       released.replace(b'https://geo.', b'https://custom.')):
            with self.subTest(edited=edited[:80]):
                self.mirrors.write_bytes(edited)
                self.refresh()
                self.assertEqual(self.mirrors.read_bytes(), edited)
                self.assertFalse(self.state.exists())
        self.assertEqual(self.calls, [])

    def test_short_legacy_installer_lists_are_adopted(self):
        for count in (1, 2):
            with self.subTest(count=count):
                self.state.unlink(missing_ok=True)
                self.calls.clear()
                legacy = b''.join(LEGACY.splitlines(keepends=True)[:2 + count])
                self.mirrors.write_bytes(legacy)
                self.refresh()
                self.assertEqual(self.mirrors.read_bytes(), FRESH)
                self.assertEqual(self.state.read_text(), POLICY['digest'](FRESH))
                self.assertEqual(len(self.calls), 1)

    def test_invalid_legacy_installer_lists_are_not_adopted(self):
        for content in (b''.join(LEGACY.splitlines(keepends=True)[:2]),
                        LEGACY.replace(b'https:', b'http:'),
                        LEGACY.replace(b'$repo', b'core'),
                        LEGACY + b'Include = /custom/list\n', LEGACY + b'\xff'):
            with self.subTest(content=content):
                self.mirrors.write_bytes(content)
                self.refresh()
                self.assertEqual(self.mirrors.read_bytes(), content)
                self.assertFalse(self.state.exists())
        self.assertEqual(self.calls, [])

    def test_custom_unknown_lists_are_not_enrolled(self):
        for content in (FRESH, LEGACY.replace(b'--latest 10', b'--latest 20'),
                        LEGACY.replace(b' --save ', b' --country Germany --save ')):
            with self.subTest(content=content):
                self.mirrors.write_bytes(content)
                self.refresh()
                self.assertEqual(self.mirrors.read_bytes(), content)
                self.assertFalse(self.state.exists())
        self.assertEqual(self.calls, [])

    def test_local_edits_after_first_refresh_stop_future_writes(self):
        self.refresh()
        edited = FRESH + b'# Keep this local choice.\n'
        self.mirrors.write_bytes(edited)
        self.refresh()
        self.assertEqual(self.mirrors.read_bytes(), edited)
        self.assertEqual(len(self.calls), 1)

    def test_installer_can_record_offline_list_for_first_automatic_refresh(self):
        self.mirrors.write_bytes(FRESH)
        self.refresh(record=True)
        self.assertEqual(self.calls, [])
        self.assertEqual(self.state.read_text(), POLICY['digest'](FRESH))
        self.refresh()
        self.assertEqual(len(self.calls), 1)

    def test_failure_keeps_original_and_removes_temporary_files(self):
        for result in (b'', b'# none\n', b'garbage\n', b'\xff',
                       FRESH.replace(b'https:', b'http:'),
                       b'Server = https://one.invalid/$repo/os/$arch\n' * 3,
                       b'Server = https://one.invalid/$repo/os/$arch\n',
                       b'Server = https://one.invalid/$repo/os/$arch\n'
                       b'Server = https://two.invalid/$repo/os/$arch\n', 'timeout', 'failed'):
            with self.subTest(result=result):
                def probe(command, **options):
                    if result == 'timeout':
                        raise subprocess.TimeoutExpired(command, 60)
                    if result == 'failed':
                        raise subprocess.CalledProcessError(1, command)
                    Path(command[-1]).write_bytes(result)
                with self.assertRaises((ValueError, subprocess.SubprocessError)):
                    self.refresh(probe)
                self.assertEqual(self.mirrors.read_bytes(), LEGACY)
                self.assertEqual(list(self.state.parent.iterdir()), [self.state])

    def test_edit_during_network_probe_is_preserved(self):
        def probe(command, **options):
            self.run_probe(command, **options)
            self.mirrors.write_bytes(b'# Local edit during probe.\n')
        self.refresh(probe)
        self.assertEqual(self.mirrors.read_bytes(), b'# Local edit during probe.\n')

    def test_symlinked_mirror_or_state_is_untouched(self):
        target = self.root / 'custom'
        target.write_bytes(LEGACY)
        self.mirrors.unlink()
        self.mirrors.symlink_to(target)
        self.refresh()
        self.assertEqual(self.calls, [])
        self.assertEqual(target.read_bytes(), LEGACY)
        self.mirrors.unlink()
        self.mirrors.write_bytes(LEGACY)
        self.state.parent.mkdir(parents=True)
        self.state.symlink_to(target)
        self.refresh()
        self.assertEqual(self.calls, [])
        self.assertEqual(target.read_bytes(), LEGACY)

    def test_real_service_execstart_with_protected_home(self):
        """Run the packaged command and reflector in a disposable service sandbox."""
        if not shutil.which('bwrap') or not shutil.which('systemd-analyze'):
            self.skipTest('bwrap and systemd-analyze are required')
        package = os.environ.get('EMAKI_TEST_REFLECTOR_ROOT')
        reflector = (Path(package) / 'usr/bin/reflector' if package
                     else Path(shutil.which('reflector') or '/nonexistent/reflector'))
        if not reflector.is_file():
            self.skipTest('real reflector is not installed; set EMAKI_TEST_REFLECTOR_ROOT')
        probe = subprocess.run(['bwrap', '--ro-bind', '/', '/', '--unshare-user',
                                '--uid', '0', '--gid', '0', '/usr/bin/true'],
                               capture_output=True, text=True)
        if probe.returncode:
            self.skipTest('unprivileged namespaces unavailable: ' + probe.stderr.strip())
        service = ROOT / 'systemd/emaki-refresh-mirrors.service'
        unit = configparser.ConfigParser(interpolation=None)
        unit.read(service)
        settings = unit['Service']
        self.assertEqual(settings['ProtectHome'], 'yes')
        self.assertEqual(settings['ProtectSystem'], 'strict')
        self.assertEqual(settings['PrivateTmp'], 'yes')
        self.assertEqual(settings['NoNewPrivileges'], 'yes')
        self.state.parent.mkdir(parents=True)
        cache = self.root / 'cache'
        cache.mkdir()
        # Cached status avoids external network access; loopback port 9 rejects
        # rate probes without suppressing real reflector code.
        status = {'last_check': '2026-01-01T00:00:00Z', 'urls': [
            {'url': f'https://127.0.0.1:9/mirror{i}/', 'protocol': 'https',
             'last_sync': '2026-01-01T00:00:00Z', 'completion_pct': 1.0}
            for i in range(3)]}
        (cache / 'mirrorstatus.json').write_text(json.dumps(status))
        cache_parent = self.root / 'var/cache'
        (cache_parent / 'reflector').mkdir(parents=True)
        protected = self.root / 'protected'
        protected.mkdir()
        binaries = self.root / 'bin'
        binaries.mkdir()
        for binary in Path('/usr/bin').iterdir():
            (binaries / binary.name).symlink_to('/tmp/host-bin/' + binary.name)
        for name, source in (('emaki-refresh-mirrors', ROOT / 'upkeep/emaki-refresh-mirrors'),
                             ('reflector', reflector)):
            destination = binaries / name
            destination.unlink(missing_ok=True)
            shutil.copy2(source, destination)
        command = ['bwrap', '--die-with-parent', '--unshare-user', '--unshare-pid',
                   '--unshare-ipc', '--unshare-uts', '--uid', '0',
                   '--gid', '0', '--cap-drop', 'ALL', '--ro-bind', '/', '/',
                   '--proc', '/proc', '--dev', '/dev', '--tmpfs', '/tmp',
                   '--ro-bind', str(self.root / 'var/lib'), '/var/lib',
                   '--ro-bind', str(cache_parent), '/var/cache',
                   '--ro-bind', str(protected), '/root',
                   '--ro-bind', str(protected), '/home',
                   '--ro-bind', '/usr/bin', '/tmp/host-bin',
                   '--ro-bind', str(binaries), '/usr/bin',
                   '--unsetenv', 'HOME', '--unsetenv', 'XDG_CACHE_HOME',
                   '--setenv', 'PATH', '/usr/bin']
        if package:
            modules = list((Path(package) / 'usr/lib').glob('python*/site-packages'))
            self.assertEqual(len(modules), 1)
            # /home is hidden: expose only the extracted module directory.
            command += ['--ro-bind', str(modules[0]), '/tmp/reflector-python',
                        '--setenv', 'PYTHONPATH', '/tmp/reflector-python']
        for directory in shlex.split(settings['ReadWritePaths']):
            source = self.root / directory.lstrip('/')
            source.mkdir(parents=True, exist_ok=True)
            command += ['--bind', str(source), directory]
        for directory in shlex.split(settings.get('CacheDirectory', '')):
            command += ['--bind', str(cache), '/var/cache/' + directory]
        for assignment in shlex.split(settings.get('Environment', '')):
            key, value = assignment.split('=', 1)
            command += ['--setenv', key, value]
        command += ['--ro-bind', str(service), '/tmp/emaki-refresh-mirrors.service']
        verify = subprocess.run(command + ['systemd-analyze', 'verify',
                                '/tmp/emaki-refresh-mirrors.service'],
                                capture_output=True, text=True)
        if verify.returncode and 'SO_PASSCRED' in verify.stderr and 'Operation not permitted' in verify.stderr:
            warnings.warn('systemd-analyze verify blocked by socket restrictions: ' +
                          verify.stderr.strip())
        else:
            self.assertEqual(verify.returncode, 0, verify.stderr)
        result = subprocess.run(command + shlex.split(settings['ExecStart']),
                                capture_output=True, text=True, timeout=30,
                                umask=int(settings['UMask'], 8))
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self.mirrors.read_bytes().count(b'Server = '), 3)
        self.assertIn(b'https://127.0.0.1:9/mirror0/', self.mirrors.read_bytes())
        self.assertEqual(self.state.read_text(), POLICY['digest'](self.mirrors.read_bytes()))

    def test_service_and_timer_use_bounded_weekly_refresh(self):
        service = (ROOT / 'systemd/emaki-refresh-mirrors.service').read_text()
        timer = (ROOT / 'systemd/emaki-refresh-mirrors.timer').read_text()
        self.assertIn('ExecStart=/usr/bin/emaki-refresh-mirrors\n', service)
        self.assertIn('TimeoutStartSec=90\n', service)
        self.assertIn('CacheDirectory=reflector\n', service)
        self.assertIn('Environment=XDG_CACHE_HOME=/var/cache/reflector\n', service)
        self.assertIn('OnCalendar=weekly\n', timer)
        self.assertIn('Persistent=true\n', timer)
        self.assertIn('WantedBy=timers.target\n', timer)


if __name__ == '__main__':
    unittest.main()
