[options]
Architecture = auto
SigLevel = Required DatabaseOptional TrustedOnly
LocalFileSigLevel = Required TrustedOnly

[emaki-offline]
SigLevel = Required DatabaseOptional TrustedOnly
Server = file:///run/archiso/bootmnt/emaki/repo
