# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
# User generators read this before generating XDG autostart units, including on reload.
XDG_CONFIG_DIRS=/usr/share/emaki/xdg:${XDG_CONFIG_DIRS:-/etc/xdg}
