# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
# Choose stable or testing [update channel].
# After switching channels, run `sudo pacman -Syyu` once.
Include = /usr/share/emaki/mirrors/stable.conf
# Include = /usr/share/emaki/mirrors/testing.conf
