#!/bin/sh
# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
# Save across every sleep mode: suspend-then-hibernate may choose either path.
case "$1" in
    pre|post) exec /usr/bin/emaki-boot-refresh --sleep-phase "$1" ;;
esac
