# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
[Unit]
Wants=emaki-wallet-start.service emaki-wallet-migrate.service

[Service]
ExecStartPre=-@EMAKI_BINDIR@/emaki-wallet-start --prepare
TimeoutStartSec=150
ExecStopPost=-@EMAKI_BINDIR@/emaki-wallet-start --stop
ExecStopPost=-systemctl --user unset-environment PAM_KWALLET5_LOGIN
