# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
[Unit]
Wants=emaki-wallet-start.service emaki-wallet-migrate.service

[Service]
ExecStartPre=-/usr/bin/emaki-wallet-start --prepare
TimeoutStartSec=150
ExecStopPost=-/usr/bin/emaki-wallet-start --stop
ExecStopPost=-/usr/bin/systemctl --user unset-environment PAM_KWALLET5_LOGIN
