[options]
Architecture = x86_64
SigLevel = Required DatabaseOptional TrustedOnly
LocalFileSigLevel = Required TrustedOnly

[emaki-offline]
SigLevel = Required DatabaseOptional TrustedOnly
Server = file:///@EMAKI_OFFLINE_REPO@

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
