# Copyright (C) 2026 Artur Yakymenko
# SPDX-License-Identifier: GPL-3.0-or-later
# mkinitcpio resolves KERNELVERSION before sourcing drop-ins, for each preset.
# Leave hibernation resume ordering intact by loading NVIDIA after initramfs.
# Keep the native hooks/modules. A failed module build must not request missing
# modules and replace an otherwise usable initramfs with an incomplete image.
if [[ " ${HOOKS[*]} " != *" emaki-resume "* ]] &&
   [[ -n ${KERNELVERSION:-} ]] &&
   modinfo -k "$KERNELVERSION" nvidia >/dev/null 2>&1 &&
   modinfo -k "$KERNELVERSION" nvidia_modeset >/dev/null 2>&1 &&
   modinfo -k "$KERNELVERSION" nvidia_uvm >/dev/null 2>&1 &&
   modinfo -k "$KERNELVERSION" nvidia_drm >/dev/null 2>&1; then
    MODULES+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
fi
